### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by girishadurrel** [Dynalon/tcp_probe_fixed#3]
I tried compiling the code and came across this error msg. Any help will be very much appreciated :)

make -C /lib/modules/3.13.0-48-generic/build  M=/home/ubuntu/Projects/tcp_probe_fixed modules
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-48-generic'
  CC [M]  /home/ubuntu/Projects/tcp_probe_fixed/tcp_probe_fixed.o
/home/ubuntu/Projects/tcp_probe_fixed/tcp_probe_fixed.c: In function ‘copy_to_tcp_probe’:
/home/ubuntu/Projects/tcp_probe_fixed/tcp_probe_fixed.c:102:14: error: ‘const struct tcp_sock’ has no member named ‘srtt_us’
  p->srtt = tp->srtt_us >> 3;
              ^
make[2]: *** [/home/ubuntu/Projects/tcp_probe_fixed/tcp_probe_fixed.o] Error 1
make[1]: *** [_module_/home/ubuntu/Projects/tcp_probe_fixed] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-48-generic'
make: *** [default] Error 2

**Comment by danielotte** [comment]
Edit tcp_probe_fixed.o  line 102 and change 
p->srtt = tp->srtt_us >> 3;     to      p->srtt = tp->srtt >> 3; 
compiling again
Cheers

**Comment by girishadurrel** [comment]
worked like a charm. Thank you
